### ISSUE TITLE
Windows line ending error (/bin/sh^M: bad interpreter) when running jsoar in linux

### ISSUE THREAD

**Issue by KRaizer** [soartech/jsoar#105]
Hello, I would like to report an issue I faced when trying to run jsoar release 0.14 in a linux machine, and what I did to solve it here:

Went to: http://soartech.github.io/jsoar/

Clicked on "Get Release" which led me to: https://github.com/soartech/jsoar/releases/tag/jsoar_0_14_0_release

Downloaded: https://github.com/soartech/jsoar/releases/download/jsoar_0_14_0_release/jsoar-0.14.0.zip

Extracted it, went to /bin abd ran: sudo chmod +x jsoar

Ran: ./jsoar

Which produced: 
username@username-VirtualBox:~/Downloads/jsoar-snapshot-0.14.0/bin$ ./jsoar
bash: ./jsoar: /bin/sh^M: bad interpreter: No such file or directory

To fix it I had to open jsoar in gedit, and "save as" altering the line ending configuration from windows to unix/linux.

Is there another way to do it?

**My System info:**
username@username-VirtualBox:~$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:    vivid

username@username-VirtualBox:~$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK Client VM (build 24.95-b01, mixed mode, sharing)

username@username-VirtualBox:~$ javac -version
javac 1.7.0_95

username@username-VirtualBox:~$ ant -version
Apache Ant(TM) version 1.9.4 compiled on January 27 2015

**Comment by marinier** [comment]
I believe line endings for linux/unix files will be fixed in the next release (they should be fixed in git now).
