### ISSUE TITLE
Test error when building JSOAR

### ISSUE THREAD

**Issue by KRaizer** [soartech/jsoar#106]
Hello, this is a problems I faced when trying to build JSOAR from code. It seems one or some of the tests are failing. This is what I did step by step:

 I went to: https://github.com/soartech/jsoar

Downloaded: jsoar-master.zip

Extracted it to: /home/username/Downloads

Went to: ~/Downloads/jsoar-master

Executed: ant

It starts a number of junit tests, and fails at one of them:

BUILD FAILED
/home/username/Downloads/jsoar-master/build.xml:4: The following error occurred while executing this line:
/home/username/Downloads/jsoar-master/jsoar-build/build.xml:84: The following error occurred while executing this line:
/home/username/Downloads/jsoar-master/jsoar-build/build-common.xml:121: Tests failed

Total time: 1 minute 30 seconds
username@username-VirtualBox:~/Downloads/jsoar-master$

Therefore, the build also failed.

Is it realy an error or is it something wrong with my system?
Any suggestions on how to proceed?

**My System info:**

username@username-VirtualBox:~$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:    vivid

username@username-VirtualBox:~$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK Client VM (build 24.95-b01, mixed mode, sharing)

username@username-VirtualBox:~$ javac -version
javac 1.7.0_95

username@username-VirtualBox:~$ ant -version
Apache Ant(TM) version 1.9.4 compiled on January 27 2015

**Comment by marinier** [comment]
Note that the master branch is no longer maintained, and instead you should use the maven branch. As of JSoar 4.0.0, dependencies can be pulled down from maven central. The [Releases](https://github.com/soartech/jsoar/releases) also contain pre-built jars.
