### ISSUE TITLE
License for JSoar ?

### ISSUE THREAD

**Issue by rgudwin** [soartech/jsoar#107]
I was not able to find a license for JSoar. May I assume the same BSD license applied to Soar is valid for JSoar ?

**Comment by rgudwin** [comment]
Follow-up ... I just found a license.txt file hidden in  jsoar/jsoar-build/resources/license.txt
Maybe you should move (or copy it) to the repository root, to make it easily available.

**Comment by marinier** [comment]
The license has been moved to the top level, and there's even a badge for it in the README now.
