### ISSUE TITLE
Error: While initializing smem ... SQL error or missing database

### ISSUE THREAD

**Issue by KRaizer** [soartech/jsoar#108]
Hello, I am getting the following error when running a simple "hello world" JSOAR program:

Error: While initializing smem: Failed to prepare statement 'SELECT tsh_a.symbol_type AS attr_type, tsh_a.s_id AS attr_hash, vcl.symbol_type AS value_type, vcl.s_id AS value_hash, vcl.soar_letter AS value_letter, vcl.soar_number AS value_num, vcl.value_lti_id AS value_lti FROM ((smem_augmentations w LEFT JOIN smem_symbols_type tsh_v ON w.value_constant_s_id=tsh_v.s_id) vc LEFT JOIN smem_lti AS lti ON vc.value_lti_id=lti.lti_id) vcl INNER JOIN smem_symbols_type tsh_a ON vcl.attribute_s_id=tsh_a.s_id WHERE lti_id=?': [SQLITE_ERROR] SQL error or missing database (ambiguous column name: lti_id)

I tried setting smem off like this: smem --set learning off
But nothing changed.

Am I missing something?

Regards,

Klaus

**Comment by marinier** [comment]
Can you send the file(s) you are using for your hello world program? Also, what OS and jsoar version are you using?

Thanks,
Bob

**Comment by KRaizer** [comment]
Hello, thanks for you help.

Here is a zip with the files I'm using:

[SoarAgent.zip](https://github.com/soartech/jsoar/files/910084/SoarAgent.zip)

I'm in a windows system, and to compile it I run:

javac -cp ".;*;" SoarAgent.java

And to run it I use:

java -cp ".;*;" SoarAgent

If I don't add "sqlite-jdbc-3.16.1.jar" as well, it produces the following error:

Error: While initializing smem: Failed to load database driver class: org.sqlite
.JDBC
Error: While initializing smem: Failed to load database driver class: org.sqlite
.JDBC

**Comment by AlexNickels** [comment]
Klaus,

The easiest solution for now is to simply not include the sqlite-jdbc-3.16.1.jar.  You will still see an error appear in the console, but it will be much shorter and it will not impact the running of the agent.

Longer term, I think I know what causes this and I have an in-house fix for it.  I will plan on releasing it sometime in the near future.
Alex Nickels

**Comment by KRaizer** [comment]
Ok, I'll do that then.
Thanks!!
