### ISSUE TITLE
Maven Access denied error with JSoar 0.14.8 release

### ISSUE THREAD

**Issue by mitchshack** [soartech/jsoar#109]
When trying to build the JSoar 0.14.8 release via maven I'm getting the following failure in jsoar-core:

[ERROR] Failed to execute goal on project jsoar-core: Could not resolve dependencies for project com.soartech:jsoar-core:jar:0.14.8: 
Failed to collect dependencies for [commons-beanutils:commons-beanutils:jar:1.8.3 (compile), org.xerial:sqlite-jdbc:jar:3.7.2-macfix (compile), org.slf4j:jcl-over-slf4j:jar:1.7.5 (compile), org.apache.commons:commons-math3:jar:3.2 (compile), com.googlecode.json-simple:json-simple:jar:1.1.1 (compile), org.springframework:spring-core:jar:4.3.2.RELEASE (compile), com.google.guava:guava:jar:18.0 (compile), org.slf4j:slf4j-api:jar:1.7.5 (compile), ch.qos.logback:logback-classic:jar:1.0.13 (runtime), junit:junit:jar:4.12 (compile)]: 
Failed to read artifact descriptor for org.xerial:sqlite-jdbc:jar:3.7.2-macfix: Could not transfer artifact org.xerial:sqlite-jdbc:pom:3.7.2-macfix from/to soartech-internal (https://nexus.soartech.com:8443/nexus/content/groups/internal/): 
Access denied to https://nexus.soartech.com:8443/nexus/content/groups/internal/org/xerial/sqlite-jdbc/3.7.2-macfix/sqlite-jdbc-3.7.2-macfix.pom. 
Error code 401, Unauthorized -> [Help 1]

It looks like the maven pom is referencing an internal SoarTech maven repository and therefore producing an "Access denied" message for users without access to the SoarTech internal Nexus repository.

Can the jsoar maven pom's be modified to refer only to externally available resources?

**Comment by marinier** [comment]
Hi,

Sorry for the inconvenience, it’s on our todo list to address this. In the meantime, I wonder if you need to build yourself, or if you can just use the pre-built binaries?

https://github.com/soartech/jsoar/releases/tag/jsoar-0.14.8

If you need to build yourself and you’re not on a mac, you can probably just change the pom to use org.xerial:sqlite-jdbc version 3.7.2 (i.e., remove the macfix part).

Bob

**Comment by adeschamps** [comment]
I've encountered this before. Removing the SoarTech repositories from the pom and dropping the `-macfix` suffix worked for me.

**Comment by heikefn** [comment]
I have solved "Could not transfer artifact org.xerial:sqlite-jdbc:pom:3.7.2-macfix from/to soartech-internal "  this error, but below error occur:"Failed to read artifact descriptor for edu.umich.soar:sml:jar:9.3.2: Could not transfer artifact edu.umich.soar:sml:pom:9.3.2 from/to soartech-internal ". 


There are some build logs:

[INFO] Reactor Summary for jsoar 0.14.8:
[INFO]
[INFO] jsoar .............................................. SUCCESS [  2.249 s]
[INFO] jsoar-core ......................................... SUCCESS [01:00 min]
[INFO] jsoar-debugger ..................................... SUCCESS [ 51.414 s]
[INFO] jsoar-demos ........................................ SUCCESS [02:06 min]
[INFO] jsoar-legilimens ................................... SUCCESS [ 48.574 s]
[INFO] jsoar-soar2soar .................................... SUCCESS [ 48.106 s]
### [INFO] jsoar-soarunit ..................................... FAILURE [01:27 min]
[INFO] jsoar-tcl .......................................... SKIPPED
[INFO] jsoar-build ........................................ SKIPPED
[INFO] jsoar-ruby ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:05 min
[INFO] Finished at: 2019-01-18T19:44:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jsoar-soarunit: Could not resolve dependencies for project com.soartech:jsoar-soarunit:jar:0.14.8: Failed to collect dependencies at edu.umich.soar:sml:jar:9.3.2: Failed to read artifact descriptor for edu.umich.soar:sml:jar:9.3.2: Could not transfer artifact edu.umich.soar:sml:pom:9.3.2 from/to soartech-internal (https://nexus.soartech.com:8443/nexus/content/groups/internal/): Connect to nexus.soartech.com:8443 [nexus.soartech.com/12.33.238.105] failed: Connection timed out: connect -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jsoar-soarunit: Could not resolve dependencies for project com.soartech:jsoar-soarunit:jar:0.14.8: Failed to collect dependencies at edu.umich.soar:sml:jar:9.3.2
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:269)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at ......


Can you help me to solve this qestion? Thank you.

**Comment by marinier** [comment]
Yes, unfortunately the currently released code doesn’t build outside of soartech. We plan to push a new version of the code soon. In the meantime, you can use pre-built releases from here:

https://github.com/soartech/jsoar/releases

Bob

**Comment by marinier** [comment]
With the jsoar 4.0.0 release, the code now builds outside of SoarTech and is available on maven central.
