### ISSUE TITLE
Is there any way to access an agent's semantic memory through Java code?

### ISSUE THREAD

**Issue by zywind** [soartech/jsoar#110]
Hi,

We are trying to write some Java code that will use the activation value of the semantic memory items. Is there a recommended way to do that? The org.jsoar.kernel.agent class has a method for accessing the agent's working memory module, but there seems to be no method for accessing its semantic memory module.

**Comment by marinier** [comment]
If you look at, e.g., how WorkingMemory.initialize gets access to semantic memory, it does this:

this.smem = Adaptables.adapt(context, SemanticMemory.class);

Where context is the agent (org.jsoar.kernel.agent). That said, I’m not sure that the SemanticMemory interface or DefaultSemanticMemory class are going to give you access to what you want. But you could always change those to make something publicly accessible if you need it.

Bob

**Comment by zywind** [comment]
Thank you. After some dig around, I think I do have to modify the DefaultSemanticMemory to get activations. Thanks for the suggestion.
