### ISSUE TITLE
How to use Reinforcement learning in jsoar ?

### ISSUE THREAD

**Issue by harit7** [soartech/jsoar#112]
I saw in the soar tutorials one needs to set some configurations like the following using the debugger. 
rl --set learning on
indifferent-selection –-epsilon-greedy
How does one set such options in jsoar? 
How can one plugin a custom RL algorithm into jsoar/soar ?

**Comment by marinier** [comment]
Reinforcement learning is mostly implemented the same in jsoar as in csoar, with the exception of some more recent command changes in csoar that have not yet been ported to jsoar.

“rl --set learning on” works in jsoar.

The indifferent-selection command has not been implemented in jsoar.

If you want to change how RL works, you need to modify the source code and rebuild. The code for RL in jsoar is here:

https://github.com/soartech/jsoar/tree/master/jsoar-core/src/main/java/org/jsoar/kernel/learning/rl

Bob

**Comment by harit7** [comment]
I am trying to run the simple water-jug-rl agent which comes in the soar tutorial. 
As you pointed out, it doesn't recognize indifferent-selection command.
Moreover it is also not recognizing 'gp' command.  Has anyone run this agent using jsoar ?

**Comment by marinier** [comment]
Probably not. The gp command isn’t supported, but also isn’t necessary – you can just use template rules instead. The only difference is whether the RL rules are pregenerated or generated as needed. For systems with even moderately complex RL rules, it’s almost certainly better to use template rules, as you can easily end up with hundreds of thousands or millions of pre-generated rules, which can drastically slow down the loading of your rules.

Bob

**Comment by harit7** [comment]
Thanks @marinier .  Template rules worked.
In the soar tutorial (part 6), I read that we need to set the value of epsilon by using the following command. 
`indifferent-selection --epsilon <value>`
Since this command is not available in jsoar, is there any other way to set it?

**Comment by marinier** [comment]
It looks like the command names have changed and the tutorial is out-of-date. You can do this with:

decide indifferent-selection --epsilon <value>

It looks like there are a lot of other parameters in there as well that may work through that command. If you type just “decide”, you’ll see the current values.

**Comment by marinier** [comment]
Sorry, it looks like those changes are very recent and have not yet been publicly released. Let me look into getting those pushed publicly.

From: Bob Marinier
Sent: Friday, November 17, 2017 10:02 AM
To: 'soartech/jsoar' <reply@reply.github.com>
Subject: RE: [soartech/jsoar] How to use Reinforcement learning in jsoar ? (#112)

It looks like the command names have changed and the tutorial is out-of-date. You can do this with:

decide indifferent-selection --epsilon <value>

It looks like there are a lot of other parameters in there as well that may work through that command. If you type just “decide”, you’ll see the current values.

**Comment by marinier** [comment]
I just posted a new release which has the “decide” command, which should make it possible to set many of the RL params:

https://github.com/soartech/jsoar/releases/tag/jsoar-0.14.9

From: Bob Marinier
Sent: Friday, November 17, 2017 10:05 AM
To: 'soartech/jsoar' <reply@reply.github.com>
Subject: RE: [soartech/jsoar] How to use Reinforcement learning in jsoar ? (#112)

Sorry, it looks like those changes are very recent and have not yet been publicly released. Let me look into getting those pushed publicly.

From: Bob Marinier
Sent: Friday, November 17, 2017 10:02 AM
To: 'soartech/jsoar' <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [soartech/jsoar] How to use Reinforcement learning in jsoar ? (#112)

It looks like the command names have changed and the tutorial is out-of-date. You can do this with:

decide indifferent-selection --epsilon <value>

It looks like there are a lot of other parameters in there as well that may work through that command. If you type just “decide”, you’ll see the current values.

**Comment by harit7** [comment]
Thanks @marinier, I guess logging is enabled in the jar you released, it is logging a lot. Is there someway I can disable it.

**Comment by marinier** [comment]
Logging is via slf4j and logback. To change the logging behavior, add a logback.xml file like the attached one to the same directory as the jsoar jar file and then run jsoar like this:

java "-Dlogback.configurationFile=logback.xml" -jar .\jsoar-build-0.14.9-jar-with-dependencies.jar

Bob

**Comment by KRaizer** [comment]
Not sure if my question belongs to this thread of if I should create a new one. 
But after I train the RL agent at some task, how do I persist it to disk so I can load and use it again in the future?

For instance, after running this code (not in full) to learn the simple left-right task:

------------------------------------------------------------------------------

   ThreadedAgent threaded_agent = ThreadedAgent.create();
   threaded_agent.setName("My Agent");
   threaded_agent.getPrinter().pushWriter(new OutputStreamWriter(System.out));
   ...
   SoarCommands.source(threaded_agent.getInterpreter(), "./agents/leftright.soar");
   ...
   int nEpisodes=3;
   for(int episode=0;episode<=nEpisodes;episode++){
	   threaded_agent.initialize();
	   threaded_agent.runForever();
   }
   ...
   String result = agent.getInterpreter().eval("print s1");
   ...
   String result = agent.getInterpreter().eval("print --rl");

------------------------------------------------------------------------------

I get:

   left-right*rl*left 1.000000  -0.3
   left-right*rl*right 2.000000  0.51

Which shows it has learned to prefer going to the right.

How do I save "threaded_agent" to disk and load it again?

**Comment by marinier** [comment]
The simplest thing is to "print --rl --full", which will print the full learned rules. You can then copy these to a file and source them with your agent the next time you load the agent.


In csoar you can use the output command to write the result of this command directly to a file:


output command-to-file <filename> <command>


Jsoar does't have that exact command, but it does have clog, which is similar:


clog <filename>

<commands>

clog --close


Bob


________________________________

**Comment by KRaizer** [comment]
Thanks Bob.
Your suggestion worked. Here is what I did:

	String result1 = agent.getInterpreter().eval("clog learned_rules.soar");
	String result2 = agent.getInterpreter().eval("print --rl --full");
	String result3 = agent.getInterpreter().eval("clog --close");

And the following rules where recorded to "learned_rules.soar" file:
`
sp {left-right*rl*left
    (state <s> ^name left-right ^operator <op> +)
    (<op> ^dir left ^name move)
    -->
    (<s> ^operator <op> = -0.51)
}
`
`
sp {left-right*rl*right
    (state <s> ^name left-right ^operator <op> +)
    (<op> ^dir right ^name move)
    -->
    (<s> ^operator <op> = 0.3)
}
`

Best regards,

Klaus
