### ISSUE TITLE
Is there an equivalent of "ExecuteCommandLine" in JSOAR?

### ISSUE THREAD

**Issue by KRaizer** [soartech/jsoar#113]
Hello,
In csoar I can do something like this:

result = kernel.ExecuteCommandLine("excise towers-of-hanoi*monitor", "Soar1")

Is there an equivalent way of running soar commands directly to kernel in jsoar?

**Comment by marinier** [comment]
In jsoar, you can do this:


String result = agent.getInterpreter().eval("my command");


There is no kernel object in jsoar; all the agents are independent (e.g., they can be run in separate threads). If there is an error, a SoarException will be thrown.


Bob


________________________________

**Comment by KRaizer** [comment]
Worked like a charm. 
Thank you so much.
Regards,
Klaus
