### ISSUE TITLE
Are you relying on anything in CSOAR when running JSOAR?

### ISSUE THREAD

**Issue by heikefn** [soartech/jsoar#115]
Is building and running JSOAR dependent on any source code or dependent libraries in CSOAR?Since there is a lot of kernel code for JSOAR, I can't easily find it, so I was wondering: is JNI technology used in JSOAR?Do you rely on some functions or dynamic link libraries in the CSOAR framework?
Looking forward to your reply, thank you!

**Comment by marinier** [comment]
Hi,

No, jsoar is an independent implementation of Soar and has no dependencies on csoar.

Bob
