### ISSUE TITLE
Do you have javadoc version 0.14.9?

### ISSUE THREAD

**Issue by heikefn** [soartech/jsoar#116]
I found a javadoc 0.11.0 in "http://darevay.com/jsoar/current/docs/jsoar-core/api/". And , I did not find the 0.14.9 document in "https://github.com/soartech/jsoar/tree/maven/doc". 
I wonder if it will be available as a version 0.14.9 document?

**Comment by marinier** [comment]
Sorry, the javadocs haven’t been regenerated in a while. That said, most of what’s in 0.11.0 is probably still valid. For everything else, there’s the wiki and there are often decent comments in the code for the parts that users typically use (at the very least, everything that would be in the javadocs is in the code).

When we do our next release, we’ll look at what’s involved in updating the javadocs.

**Comment by marinier** [comment]
Note that Javadocs and source are now available in the jsoar 4.0.0 jars on maven central, and also the javadocs are linked from the [README](https://github.com/soartech/jsoar/blob/maven/README.md).
