### ISSUE TITLE
jSoar 4.0 Release

### ISSUE THREAD

**Issue by mldavis99** [soartech/jsoar#125]
The jSoar 4.0 Release Notes say that the new release is available on Maven Central.  Not being a Java developer, can you tell me how to get the release and how to install it on Windows 10?

**Comment by marinier** [comment]
If you just want to download it and run it (e.g., to play around), you can get it from [the Releases tab on github](https://github.com/soartech/jsoar/releases). The thing you want in this case is ` jsoar-debugger-4.0.0-uber.jar` -- this is a standalone jar you can just run (e.g., by double-clicking) and it will open the debugger with a running Soar instance inside.

If you want to actually develop code that uses jSoar, then I recommend setting up a project that uses a dependency manager. There are many, but the most common for java are [Maven](https://maven.apache.org/) and [Gradle](https://gradle.org/). Note that they both work with maven central. Most IDEs (e.g., Eclipse, Intellij, etc.) will have support for dependency tools like this. The [README](https://github.com/soartech/jsoar/blob/maven/README.md) shows what to put in your maven pom or .gradle file (also on the [main jsoar github page](https://github.com/soartech/jsoar).

Does that help?

**Comment by mldavis99** [comment]
Thank you, got the jsoar-debugger-4.0.0-uber.jar, however, the last version I was able to run on Windows 10 was 0.14.3 using the scripts in the bin directory. How do I do this with the ...uber.jar?
OOPs  got it:  java -jar jsoar-debugger-4.0.0-uber.jar  .  Maybe I should stick to languages I actually know.  But I am actually learning Soar right now...  Thank you very much, mike
