### ISSUE TITLE
links broken in JSoarScripting

### ISSUE THREAD

**Issue by EngrStudent** [soartech/jsoar#126]
I was here:
https://github.com/soartech/jsoar/wiki/JSoarScripting 

I tried to look at the python code example link here:
https://github.com/soartech/jsoar/blob/master/jsoar-demos/demos/scripting/waterjugs-py.soar

And it gave a 404 error.

After some looking I found the correct link here:
https://github.com/soartech/jsoar/tree/maven/jsoar-demos/demos/scripting

**Comment by marinier** [comment]
Thank you for finding the broken links and the fix! That wiki page has been updated. I'll make another issue to scrub the rest of the wiki.
