### ISSUE TITLE
Clear and Re-populate Qmemory Path without state no-change

### ISSUE THREAD

**Issue by rezamini** [soartech/jsoar#135]
Hello everyone,

I am currently developing an agent with the help of Qmemory. I read through soar tutorials and tried replicating the same scenarios with my agent. My question is when is the best time to clear and re-populate the memory path? I want to achieve something similar to Eater's ^my-location, it is stated in the tutorial that it re-populates even if the values are identical.

Please note I have tried multiple ways and got it worked by removing the memory path in onCommandAdded method which is part of OutputCommandHandler, and then updating the memory on the InputEvent listener. But this created a state-no-change when I step/run the agent. In other words, for example, I have to step twice before the agent moves and the path to re-populate again, so the agent could propose the operator. Similar to move-to-food operators for my-location in the Eater tutorial.

I have also tried removing and updating the memory on different events but no luck so far. I have also looked into a similar question #111 but it did not help.

Any help or advice would be much appreciated. Thank you.

**Comment by marinier** [comment]
Can you share your code? It's hard to say what's wrong in the abstract.

It may also help to look at the QMemory tests, which should demonstrate a lot of the functionality:

[DefaultQMemoryTest.java](..//blob/maven/jsoar-core/src/test/java/org/jsoar/kernel/io/quick/DefaultQMemoryTest.java)
[SoarQMemoryAdapterTest.java](../blob/maven/jsoar-core/src/test/java/org/jsoar/kernel/io/quick/SoarQMemoryAdapterTest.java)

**Comment by rezamini** [comment]
@marinier thank you for your prompt reply.

I have made a simple class to demonstrate what I explained above, specifically where I update and delete the memory path. Please note that the agent would eventually run & step indefinitely but it generates state no-change on every move. Thank you for your help in advance.

`    public class Agent {
      private final ThreadedAgent threadedAgent;
      private final QMemory qMemory = DefaultQMemory.create();
   
     public Agent() {
        threadedAgent = ThreadedAgent.create();

        try {
            SoarQMemoryAdapter.attach(threadedAgent.getAgent(), getQMemory());
            new CycleCountInput(threadedAgent.getInputOutput());

            initCommandHandler();
            initCommandListener("move");
            initInputEventListener();

            threadedAgent.initialize();
  
            File source = new File(getClass().getResource("path-to-file").toURI());

            if (source != null) {
                final Callable<Void> call = () -> {
                    SoarCommands.source(threadedAgent.getInterpreter(), source);
                    return null;
                };
                threadedAgent.execute(call, null);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void initCommandHandler() {
        final SoarBeanOutputManager manager = new SoarBeanOutputManager(threadedAgent.getEvents());
        final SoarBeanOutputHandler<Move> handler = new SoarBeanOutputHandler<Move>() {

            @Override
            public void setExceptionHandler(SoarBeanExceptionHandler handler) {
                super.setExceptionHandler(handler);
            }

            @Override
            public void handleOutputCommand(SoarBeanOutputContext context, Move bean) {
                bean.setDirection(context.getCommand().getChildren().next().getValue().toString());
                context.setStatus("complete");
            }
        };
        manager.registerHandler("move", handler, Move.class);
    }

    private void initCommandListener(String commandNameToListen) {
        OutputCommandManager outputManager = new OutputCommandManager(threadedAgent.getEvents());
        OutputCommandHandler handler = new OutputCommandHandler() {
            @Override
            public void onCommandRemoved(String commandName, Identifier commandId) {

            }

            @Override
            public void onCommandAdded(String commandName, Identifier commandId) {
                removeMemoryPath("area.view");

            }
        };
        outputManager.registerHandler(commandNameToListen, handler);
    }

    private void initInputEventListener() {
        threadedAgent.getEvents().addListener(InputEvent.class, new SoarEventListener() {
            @Override
            public void onEvent(SoarEvent event) {
                updateMemory();
            }
        });
    }

    private void removeMemoryPath(String path) {
        synchronized (qMemory) {
            qMemory.remove(path);
        }
    }

    public void updateMemory() {
        
        synchronized (qMemory) {
            //Multiple hierarchies here, example:
            qMemory.setString("area.view.north.type", "normal");
            qMemory.setString("area.view.south.type", "none");
            
            qMemory.setString("area.status", "active");
        }
    }

    public ThreadedAgent getThreadedAgent() {
        return threadedAgent;
    }

    public QMemory getQMemory() {
        return qMemory;
    }

    public void start() {
        threadedAgent.runForever();
    }

    public void step() {
        threadedAgent.runFor(1, RunType.DECISIONS);
    }}`

**Comment by marinier** [comment]
It appears that QMemory is designed to keep an element on the input-link rather than "blink" it if it is removed and added in the same cycle. You have a few options:

1. You can use `QMemory::clear()` -- this resets the entire memory, so clearing and re-adding in the same cycle works. I haven't specifically tested this, but you can do this for sub-memories, too, so if you only want to apply this to part of the input-link you can.
2. You can remove the elements you want to blink, run a cycle, and then re-add them. This has the downside of requiring an extra cycle to update the input-link, and your agent may require changes to deal with that.
3. You can use a different input API for updating the parts of the input-link that you need to blink. [There are several input APIs in jsoar](https://github.com/soartech/jsoar/wiki/JSoarInput) and certainly core input (the lowest level one) will let you do this, but others may as well. You can mix and match them for different parts of the input-link if you wish, so you can use qmemory for most of the input-link and use a different API for the parts that are giving you trouble.

Of these options, I'd try 1 with sub-memories first. Otherwise I'd do 3. Note that I typically don't use QMemory on "real" projects because it is actually pretty slow. That probably doesn't matter for toy agents, but it is often the case that I/O is the bottleneck in real-world agents.

BTW, as part of looking into this I found a bug in the `qmemory` command (because you can do this from the command line, in addition to your application code), so I just pushed that fix.

**Comment by rezamini** [comment]
@marinier First of all, thank you for your detailed explanation. 

Regarding the first option, I had tried it before and just re-tested it, and it seems it doesn't work. Based on the Qmemory clear() method explanation, it would just clear the value and not the path, therefore blink won't happen. I might be wrong on this, if so please let me know.

As you mentioned option two has its own downside such as the state no-change, as currently I am facing.

Therefore the third option would be an ideal way to go but it requires lots of modification as I deeply implemented the Qmemory in the application. 
To remove the path with other Input APIs, I realized it will mostly happen through the remove() method of the InputWme interface. 

For example, I have to create the InputWme like the below, with core methods or helper methods like :

`InputWme wme = InputWmes.add(io, "attr", Symbols.NEW_ID);`

and I can remove it with:

`wme.remove()`

Based on some examples and the source code I noticed I have to keep track of the InputWme creation and the structure to be able to remove it. is that correct? Is there a way to get the InputWme or cast the current wme to it, if it was created with Qmemory or any other ways? In other words, is there a helper method or a way to get the current inputWmes without having a reference to its creation?

**Comment by marinier** [comment]
The first option appears to work from the command line. There's a bug in the jsoar graphical debugger that prevents the `qmemory` command from executing properly there, but here is an execution from jsoar-repl (the text debugger):

```
soar> waitsnc --on
Soar will now wait instead of impassing when a state doesn't change.
soar> qmemory --set a.b foo

foo
soar> w 4

Trace level 4 enabled: Working memory element additions and removals
Trace level 3 enabled: All rule firings
Trace level 2 enabled: All phases, state removals caused by operator selection or a GDS violation, and any learning issues detected
Trace level 1 enabled: Decision cycles, state creation and operator selection
soar> run 1 -p

--- input phase ---
=>WM: (15: A1 ^b foo)
=>WM: (14: I2 ^a A1)
soar> qmemory --clear

soar> qmemory --set a.b foo

foo
soar> run 5 -p

--- propose phase ---
--- decision phase ---
     1: ==>S: S1 
--- apply phase ---
--- output phase ---
--- input phase ---
=>WM: (17: A2 ^b foo)
=>WM: (16: I2 ^a A2)
<=WM: (15: A1 ^b foo)
<=WM: (14: I2 ^a A1)
```
In the first decision cycle, input `a.b foo` is created. You can see the WMEs being put on the input-link during the input phase.
At this point, I clear the qmemory and re-create the same structure. In the second input phase, you can that the old WMEs are removed and new ones are added. This "blinks" the input structure. Is this not what you wanted?

**Comment by rezamini** [comment]
@marinier thank you for your reply.

To be lucid regarding my previous answer, the clear() method of qmemory correctly update the values but does not remove the entire path and is not useful for all scenarios—for example, the Eater tutorial of soar --> move-to-food operator proposal. 

The explanation of this operator can be found in "soar Tutorial Part 2 - Interacting with an agent, from page 20 onwards". As mentioned in the first comment in this issue, I want to achieve something similar to Eater's ^my-location. I previously achieved it with the remove() method but it had to run an extra cycle (it gives state no-change as well), but with the clear() method it seems the agent cant identify the re-added values. In scenarios like the "Eater" there are times when the surrounding cells and their values are the same and clearing the values apparently won't trigger the agent. I am not sure if this is a bug or the normal behavior of the agent. I am guessing this could be because the agent is expecting a new path every time, as the path is used in the proposal.

To add some extra points, both the clear and remove method works if the agent proposal is based on a specific field in memory but not an entire path with sub-memories like ^my-location.
