### ISSUE TITLE
JSoarDebugger Wiki page is missing all the pictures

### ISSUE THREAD

**Issue by rgudwin** [soartech/jsoar#140]
As it is clear from the title, the JSoarDebugger Wiki page with documentation for JSoarDebugger is missing all the pictures. Viewing the source from the Wiki page, I could detect that all the pictures are links to the https://camo.githubusercontent.com/ web page, which returns "Not found" when accessed. If these links are still valid, then there is probably a permission problem, and possibly just a few users are being able to see the pictures. An ordinary user just sees a page without any picture.

**Comment by marinier** [comment]
Thank you for noticing and reporting. I'll see if I can recover or reproduce the images when I get a chance.

**Comment by marinier** [comment]
This has been fixed.
