### ISSUE TITLE
Implement "print --exact" from csoar trunk revision 10504

### ISSUE THREAD

**Issue by voigtjr** [soartech/jsoar#6]
Port "print --exact" in https://code.google.com/p/soar/source/detail?r=10504 to jsoar.

Mostly done, left to do:
- Lexer can throw an IOException, which I currently ignore. The production parser
  code throws a ParserException when this happens, so I assume I should throw a
  PatternReaderException (which doesn't exist yet), and that PrintCommand should catch
  it and give an error message of some kind.
- Patterns currently must be wrapped in double quotes (e.g., print --exact "\* disk
  *"). This is because it is easiest to read the pattern as a single argument in
  PrintCommand. If we allowed other formats (no quotes, parens, carat before the
  attribute, etc.), then we'd have to write a little pre-parser for the pattern to get
  it constructed properly for the next step. This is what csoar does, and if we think
  that's important, we can do it, too, but I'm inclined to file this as a low-priority RFE.

**Comment by marinier** [comment]
An meaningful error is printed right now. It happens to include the name of the exception, which isn't great, but at least it says what the issue is.

The second bullet is no longer relevant. CSoar requires enclosing parens, and so does jsoar.
